apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-uploader-deployment
  labels:
    app: image-uploader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-uploader
  template:
    metadata:
      labels:
        app: image-uploader
    spec:
      containers:
        - name: image-uploader
          image: chaitanyagidijala123/image-uploader:v2 # Your Docker Hub image
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: image-storage
              mountPath: /app/uploads
      volumes:
        - name: image-storage
          persistentVolumeClaim:
            claimName: image-pvc
#        - name: image-storage # Commented out previous hostPath volume
#          hostPath:
#            path: /mnt/data/image-uploads
#            type: DirectoryOrCreate
