apiVersion: v1
kind: Service
metadata:
  name: image-uploader
spec:
  selector:
    app: image-uploader
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30002 # You can choose any port between 30000-32767
